@ECHO OFF
SET CLIPPER=F200
SET LIB=D:\CLIPPER\lib;%LIB%
SET OBJ=D:\CLIPPER\obj;%OBJ%
SET PATH=D:\CLIPPER\INCLUDE;D:\CLIPPER\BIN;%PATH%
SET INCLUDE=D:\CLIPPER\include;%INCLUDE%
Set Bin=D:\CLIPPER\bin;%lib%

