******************************************************************************

*****************************/FUN€AO CADASTRO DE NOTAS\***********************
IF CONFERE="N"
        IF ACESSO#1
        OL_Yield()
            ALERT('ACESSO NAO AUTORIZADO')
            RETURN(.T.)
        ENDIF
ENDIF
SET CENT ON
MNOTA=SPACE(10)
MDATA=DATE()
*MXML=SPACE(50)
MRECIBO=SPACE(1)
MDISTRIB=SPACE(12)
MVALORCN=0
MVALORSN=0
MVALOR_C=0
MEMP=MEMPRESA
IF CONFERE="S"
        MNOTA=VAL(MCODNOT)
        MNOTA=ALLTRIM(STR(MNOTA))
        MDATA=MCDATA
        MVALOR_C=VENDATOTAL
        MVALORCN=MPTOTG2
        MDISTRIB=RDISTRIB
ENDIF        
SETCOLOR("W+/BG,N/W")
@ 04,12 CLEAR TO 19,63
@ 04,12 TO 19,63 DOUBLE
@ 04,23 SAY "³    CADASTRO DE NOTAS   ³"
@ 05,14 SAY "NOTA:" GET MNOTA PICT "@!" VALID ! EMPTY(MNOTA)
@ 05,31 SAY "DATA NOTA:" GET MDATA PICT "@D"
MRECIBO="S"
@ 05,53 SAY "R.XML:" GET MRECIBO PICT "@!" VALID MRECIBO $ ("S/N")
@ 07,14 SAY "DISTRIB.:" GET MDISTRIB PICT "@!"
@ 09,14 SAY "VALOR_CN:" GET MVALORCN PICT "999,999.99"
@ 11,14 SAY "VALOR_SN:" GET MVALORSN PICT "999,999.99"
@ 13,14 SAY "VALOR_V.:" GET MVALOR_C PICT "999,999.99"  
@ 15,13 SAY "EMPRESA.:" GET MEMP PICT "@!" VALID MEMP $ ("1/2/3")
@ 17,13 GET MXML PICT "@!"
READ
if lastkey()=27
          RETURN
ENDIF       
NOTAS()
*IF CONFIRMA ("GRAVA ESSE REGISTRO ?")=1
            APPEND BLANK
            REPLACE NOTA     WITH MNOTA
            REPLACE DATA     WITH MDATA
            REPLACE XML      WITH MXML
            REPLACE EMP      WITH MEMP
            REPLACE RECIBO   WITH MRECIBO
            REPLACE DISTRIB  WITH MDISTRIB
            REPLACE VALORCN  WITH MVALORCN
            REPLACE VALORSN  WITH MVALORSN
            REPLACE VALOR_C  WITH MVALOR_C
*ENDIF


